### PR TITLE
Document ChiefDelphi

### PR DESCRIPTION
**Pull request by azaleacolburn**

### CODE REVIEW

**Comment by azaleacolburn** [comment]
There're a bunch of old commits that I never pulled to main, they literally have no effect anymore because they're been written over. This PR just documents and cleans up chief Delhi(for the most part).

**Comment by MeechaPooch** [comment]
This is cool! Arent some of these older commits already merged into the main branch? Would it be bad to merge them twice?

**Comment by rutmanz** [comment]
I think it would be OK if we squash it, but it might be better to rebase this branch and get that all cleaned up first

**Comment by azaleacolburn** [comment]
> This is cool! Arent some of these older commits already merged into the main branch? Would it be bad to merge them twice?

they were never merged, but they've been overwritten by newer commits in this PR

**Pull request closed without merging**
